<?php

namespace Model;

class Data
{

    public static function words(): array
    {
        return [
            'pain' => 'bread',
            'nain de jardin' => 'garden gnome',
            'oeuf' => 'egg',
            'buisson' => 'bush',
            'chapeau' => 'hat',
            'porte' => 'door',
            'musique' => 'music',
            'biscuit' => 'cookie',
            'arbre' => 'tree',
            'chat' => 'cat',
            'chien' => 'dog',
            'maison' => 'house',
            'fenetre' => 'window',
            'table' => 'table',
            'chaise' => 'chair',
            'voiture' => 'car',
            'fleur' => 'flower',
            'livre' => 'book',
            'école' => 'school',
            'crayon' => 'pencil',
            'ordinateur' => 'computer',
            'étoile' => 'star',
            'rivière' => 'river',
            'montagne' => 'mountain',
            'plage' => 'beach',
            'mer' => 'sea',
            'ciel' => 'sky',
            'soleil' => 'sun',
            'lune' => 'moon',
            'oiseau' => 'bird',
            'poisson' => 'fish',
            'cheval' => 'horse',
            'vache' => 'cow',
            'poule' => 'hen',
            'mouton' => 'sheep',
            'trampoline' => 'trampoline',
            'ballon' => 'ball',
            'jouet' => 'toy',
            'gâteau' => 'cake',
            'chocolat' => 'chocolate',
            'glace' => 'ice cream',
            'sandwich' => 'sandwich',
            'restaurant' => 'restaurant',
            'hôpital' => 'hospital',
            'pharmacie' => 'pharmacy',
            'banque' => 'bank',
            'poste' => 'post office',
            'marché' => 'market',
            'supermarché' => 'supermarket',
            'musée' => 'museum',
            'cinéma' => 'cinema',
            'théâtre' => 'theatre',
            'bateau' => 'boat',
            'avion' => 'airplane',
            'train' => 'train',
            'bus' => 'bus',
            'moto' => 'motorcycle',
            'vélo' => 'bicycle',
            'route' => 'road',
            'pont' => 'bridge',
            'tunnel' => 'tunnel',
            'gare' => 'station',
            'aéroport' => 'airport',
            'port' => 'port',
            'église' => 'church',
            'mosquée' => 'mosque',
            'temple' => 'temple',
            'synagogue' => 'synagogue',
            'quartier' => 'neighborhood',
            'rue' => 'street',
            'avenue' => 'avenue',
            'place' => 'square',
            'jardin' => 'garden',
            'piscine' => 'swimming pool',
            'parc' => 'park',
            'zoo' => 'zoo',
            'bibliothèque' => 'library',
            'centre commercial' => 'shopping center',
            'pharmacie' => 'pharmacy',
            'boulangerie' => 'bakery',
            'café' => 'café',
            'pizzeria' => 'pizzeria',
            'boucherie' => 'butcher',
            'charcuterie' => 'deli',
            'fromagerie' => 'cheese shop',
            'épicerie' => 'grocery store',
            'restaurant' => 'restaurant',
            'cuisine' => 'kitchen',
            'salon' => 'living room',
            'chambre' => 'bedroom',
            'salle de bain' => 'bathroom',
            'couloir' => 'hallway',
            'entrée' => 'entryway',
            'garage' => 'garage',
            'grenier' => 'attic',
            'cave' => 'cellar',
        ];
    }
}